{
	"version": 1671366027,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/spritefont.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/a3 long.m4a",
		"media/a3 long.ogg",
		"media/b3 long.m4a",
		"media/b3 long.ogg",
		"media/g3 long.m4a",
		"media/g3 long.ogg",
		"media/f3 long.m4a",
		"media/f3 long.ogg",
		"media/c3 long.m4a",
		"media/c3 long.ogg",
		"media/d3 long.m4a",
		"media/d3 long.ogg",
		"media/e3 long.m4a",
		"media/e3 long.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}